/**
 * Mapiranje testId -> { testType, apiOnly, requiresMailpit, mailpitSubjectFilter }
 * apiOnly = true: ne treba checkpoint, Mailpit, rollback
 * requiresMailpit = true: test šalje email - provjeri Mailpit
 * mailpitSubjectFilter: ključne riječi u subjectu očekivanog maila (case insensitive, bilo koja)
 */
export const TEST_ID_MAP = {
  '1.1': { testType: 'registration', apiOnly: false, requiresMailpit: true, mailpitSubjectFilter: ['potvrdite', 'verify', 'email adresu'] },
  '1.2': { testType: 'registration', apiOnly: false, requiresMailpit: true, mailpitSubjectFilter: ['potvrdite', 'verify', 'email adresu'] },
  '1.3': { testType: 'login', apiOnly: true },
  '1.4': { testType: 'registration', apiOnly: false, requiresMailpit: true, mailpitSubjectFilter: ['potvrdite', 'verify', 'email adresu'] },
  '1.5': { testType: 'forgot-password', apiOnly: false, requiresMailpit: true, mailpitSubjectFilter: ['reset', 'lozink', 'password'] },
  '1.6': { testType: 'jwt-auth', apiOnly: true },
  '2.1': { testType: 'categories-load', apiOnly: true },
  '2.2': { testType: 'categories-hierarchy', apiOnly: true },
  '2.3': { testType: 'jobs-filter', apiOnly: false },
  '3.1': { testType: 'job_creation', apiOnly: false },
  '3.4': { testType: 'map-picker', apiOnly: false },
  '3.5': { testType: 'job-status', apiOnly: true },
  '4.1': { testType: 'offer-send', apiOnly: false },
  '4.3': { testType: 'offer-accept', apiOnly: false },
  '6.1': { testType: 'provider-profile', apiOnly: true },
  '6.4': { testType: 'team-locations', apiOnly: false },
  '12.1': { testType: 'matchmaking', apiOnly: true },
  '14.1': { testType: 'verify-registar', apiOnly: true },
  '18.1': { testType: 'stripe-checkout', apiOnly: false },
  '18.2': { testType: 'stripe-payment', apiOnly: false },
  '18.3': { testType: 'stripe-webhook', apiOnly: true },
  '18.4': { testType: 'stripe-refund', apiOnly: false },
  '19.1': { testType: 'director-dashboard', apiOnly: true },
  '19.2': { testType: 'lead-distribution', apiOnly: true },
  '20.1': { testType: 'chat-public', apiOnly: false },
  '20.2': { testType: 'chat-internal', apiOnly: false },
  '21.1': { testType: 'sms-verify', apiOnly: false },
  '21.2': { testType: 'sms-offer', apiOnly: false },
  '21.3': { testType: 'sms-job', apiOnly: false },
  '21.4': { testType: 'sms-error', apiOnly: true },
  '22.1': { testType: 'kyc-upload', apiOnly: false },
  '22.2': { testType: 'kyc-verify-oib', apiOnly: true },
  '22.3': { testType: 'kyc-status', apiOnly: true },
  '22.4': { testType: 'kyc-reject', apiOnly: false },
  '23.1': { testType: 'portfolio-upload', apiOnly: false },
  '23.2': { testType: 'license-upload', apiOnly: false },
  '23.3': { testType: 'portfolio-display', apiOnly: true },
  '23.4': { testType: 'gallery-preview', apiOnly: false },
  '24.1': { testType: 'email-offer', apiOnly: false },
  '24.2': { testType: 'email-job', apiOnly: false },
  '24.3': { testType: 'email-trial', apiOnly: false },
  '24.4': { testType: 'email-inactivity', apiOnly: false },
  '25.1': { testType: 'saved-search', apiOnly: true },
  '25.2': { testType: 'job-alert-create', apiOnly: true },
  '25.3': { testType: 'job-alert-freq', apiOnly: true },
  '25.4': { testType: 'job-alert-notify', apiOnly: false },
  '26.1': { testType: 'admin-approve-provider', apiOnly: false },
  '26.2': { testType: 'admin-reject-provider', apiOnly: false },
  '26.3': { testType: 'admin-ban', apiOnly: false },
  '26.4': { testType: 'admin-kyc-metrics', apiOnly: true },
  '27.1': { testType: 'wizard-categories', apiOnly: true },
  '27.2': { testType: 'wizard-regions', apiOnly: true },
  '27.3': { testType: 'wizard-status', apiOnly: true },
  '27.4': { testType: 'wizard-complete', apiOnly: false },
  '28.1': { testType: 'subscription-upgrade', apiOnly: false },
  '28.2': { testType: 'subscription-downgrade', apiOnly: false },
  '28.3': { testType: 'subscription-cancel', apiOnly: false },
  '28.4': { testType: 'trial-activate', apiOnly: false },
  '29.1': { testType: 'roi-dashboard', apiOnly: true },
  '29.2': { testType: 'roi-charts', apiOnly: true },
  '29.3': { testType: 'roi-conversion', apiOnly: true },
  '29.4': { testType: 'roi-reports', apiOnly: true },
  '30.1': { testType: 'credit-buy', apiOnly: false },
  '30.2': { testType: 'credit-spend', apiOnly: false },
  '30.3': { testType: 'credit-history', apiOnly: true },
  '30.4': { testType: 'credit-refund', apiOnly: false },
  '31.1': { testType: 'cors', apiOnly: true },
  '31.2': { testType: 'csrf', apiOnly: true },
  '31.3': { testType: 'rate-limiting', apiOnly: true },
  '31.4': { testType: 'sql-injection', apiOnly: true }
};
