# Root Directory na Renderu: RegistarPoslovnihSubjekata
# Dockerfile Path: Dockerfile.prod
FROM node:20-alpine
WORKDIR /app

COPY backend/package.json backend/package-lock.json ./
RUN npm ci --omit=dev

COPY backend/src ./src
COPY backend/public ./public

ENV NODE_ENV=production
EXPOSE 3000

CMD ["node", "src/server.js"]
